[project]
name = "gateway"
version = "1.0.0"
#客户端心跳时间，单位秒
HeartbeatTime = 10000

[server]
#监听客户端地址
listenClient = "0.0.0.0:3001"
listenServer = "0.0.0.0:3002"

#目标服务器
[[backends]]
backend = ["127.0.0.1:9001"]
##前缀
filter = "/proto.GameService"
##模块
module = ["default"]


[[backends]]
backend = ["127.0.0.1:9001","127.0.0.1:9002"]
filter = "/proto.SearchService/Hello"
module = ["default"]

[[servers]]
name = "gate1"
type = "GateWay"
listenAddr = "0.0.0.0:3001"
outAddr = "0.0.0.0:3001"

[[servers]]
name = "game1"
type = "Game"
listenAddr = "0.0.0.0:9001"
outAddr = "0.0.0.0:9001"

